# Generated by Django 5.0 on 2024-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='factors',
            field=models.CharField(blank=True, choices=[('temperature', 'temp'), ('humidity', 'hum'), ('pressure', 'pres')], max_length=29, null=True),
        ),
    ]
